[project]
authors = ["Matt Fisher <mfisher87@gmail.com>"]
channels = ["conda-forge"]
name = "workshops.geojupyter.org"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
render = "myst build --html"
preview = "myst start"

[dependencies]
mystmd = ">=1.3.26,<2"
